// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tddgwnzvrlpwpyeurhuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkZGd3bnp2cmxwd3B5ZXVyaHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1MTMzNjIsImV4cCI6MjA1MDA4OTM2Mn0.2yhaGuG_IaJVcsGiJWpDTgO507nROQbe6Kz8II10cPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);